name: "Compress File"
description: "Compress a file using gzip"
inputs:
  host:
    description: "Hosting provider host"
    required: true
  username:
    description: "Hosting provider username"
    required: true
  key:
    description: "Hosting provider private key"
    required: true
  port:
    description: "Hosting provider port"
    required: true
  file:
    description: "File to compress"
    required: true
  path:
    description: "Path to the file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Compress File
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        port: ${{ inputs.port }}
        script: |
          cd ${{ inputs.path }}
          gzip -f ${{ inputs.file }}
